# Learning how to load (PIL), manipulate data (numpy)  and save them back in tiff (16bits) (PIL)

Python Imaging Library (PIL) documentation can be found [here](http://effbot.org/imagingbook/pil-index.htm)

In [1]:
from PIL import Image

%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

import time

In [86]:
filename = '/Users/j35/Desktop/image001_with_gamma.tif'

In [126]:
data = np.ones((10, 10))*10000
data = np.asarray(data, dtype=np.int16)

In [136]:
print(data.dtype)
print(data)

print("")

new_data = np.asarray(data, dtype=np.float32)
print(new_data.dtype)
print(new_data)

print("")

new_data = np.asarray(new_data, dtype=np.int16)
print(new_data.dtype)
print(new_data)

int16
[[10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 32767 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
 [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]]

float32
[[10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
 [10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
 [10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
 [10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
 [10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 1000

In [128]:
np.iinfo(data.dtype)

iinfo(min=-32768, max=32767, dtype=int16)

In [129]:
data[5, 5] = np.iinfo(data.dtype).max

In [130]:
data.dtype

dtype('int16')

In [124]:
my_file = Image.fromarray(data)
my_file.save(filename, dtype=np.int16)

In [125]:
data.dtype

dtype('int16')

checking the format of the data created

In [117]:
loaded_data = Image.open(filename)
data = np.asarray(loaded_data)

In [118]:
data.dtype

dtype('int32')

# Creating set of images 

In [ ]:
loade

In [16]:
output_folder = '/Users/j35/Desktop/ideal_water_intake_images/'
display_flag = False

In [17]:
data = np.ones([100, 100])
data[94:,:] = 0 #bottom part of image

if display_flag:
    figure = plt.figure(figsize=(5,5))
    ax_img = plt.subplot(111)

counter = 0
for index in np.arange(99,0,-1):
    data[index, 48:53] = 0
    file_name = "image_{:03}.tif".format(counter)
    counter += 1
    
    if display_flag:
        ax_img.imshow(data, 
                     cmap='viridis')
        figure.canvas.draw()
        time.sleep(1e-7)
    
    full_file_name = os.path.join(output_folder, file_name)
    my_image = Image.fromarray(data)
    my_image.save(full_file_name)    