In [20]:
import dxchange
import os

import numpy as np
import glob

In [13]:
file1 = "/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00240.tif"
file2 = "/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00241.tif"

In [14]:
assert os.path.exists(file1)
assert os.path.exists(file2)

In [15]:
data1 = dxchange.read_tiff(file1)
data2 = dxchange.read_tiff(file2)

In [16]:
print(np.shape(data1))
print(np.shape(data2))

(512, 512)
(512, 512)


In [17]:
print(type(data1))
print(type(data2))

<class 'numpy.memmap'>
<class 'numpy.memmap'>


In [18]:
print(data1)

[[11.312296 21.932407 20.94755  ... 25.480106 18.067417 19.168877]
 [22.095053 32.019516 27.63908  ... 36.828064 30.159384 32.21145 ]
 [24.307142 38.943203 33.42542  ... 37.89005  33.658417 31.06511 ]
 ...
 [72.74818  73.53404  59.650146 ... 56.78317  49.865646 33.059612]
 [59.76858  50.85497  59.84582  ... 40.479027 56.54744  37.771976]
 [38.302097 44.076775 45.94287  ... 34.099194 41.784256 42.191654]]


In [19]:
print(data2)

[[17.486906 25.07438  23.049719 ... 21.239717 23.388996 24.50194 ]
 [13.680503 24.55671  26.5859   ... 37.931313 37.719074 31.151272]
 [24.315392 27.054102 28.045195 ... 34.65909  32.58748  22.502491]
 ...
 [44.358368 61.915424 50.508778 ... 56.828205 61.251064 47.416805]
 [64.337135 59.945965 54.241024 ... 55.138855 58.857647 48.914753]
 [38.322586 36.3818   36.116165 ... 52.837685 40.707783 42.216515]]


Trying to load the entire stack

In [21]:
list_tiff = glob.glob(os.path.join("/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/", "*.tif"))

In [27]:
list_tiff.sort()
import pprint
pprint.pprint(list_tiff[0:10])

['/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00000.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00001.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00002.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00003.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00004.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00005.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00006.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00007.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle_000_000/Run_56000/Image019_00008.tif',
 '/Users/j35/SNS/SNAP/IPTS-0001/shared/autoreduce/mcp/test_Angle

In [29]:
data = []
for _index, _file in enumerate(list_tiff):
    _data = dxchange.read_tiff(_file)
    print(f"{os.path.basename(_file) =}{_index =}: {type(_data) =}")
    data.append(_data)

os.path.basename(_file) ='Image019_00000.tif'_index =0: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00001.tif'_index =1: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00002.tif'_index =2: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00003.tif'_index =3: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00004.tif'_index =4: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00005.tif'_index =5: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00006.tif'_index =6: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00007.tif'_index =7: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00008.tif'_index =8: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00009.tif'_index =9: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00010.tif'_index =10: type(_data) =<class 'nu

os.path.basename(_file) ='Image019_00097.tif'_index =97: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00098.tif'_index =98: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00099.tif'_index =99: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00100.tif'_index =100: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00101.tif'_index =101: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00102.tif'_index =102: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00103.tif'_index =103: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00104.tif'_index =104: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00105.tif'_index =105: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00106.tif'_index =106: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00107.tif'_index =107: type(

os.path.basename(_file) ='Image019_00186.tif'_index =186: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00187.tif'_index =187: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00188.tif'_index =188: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00189.tif'_index =189: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00190.tif'_index =190: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00191.tif'_index =191: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00192.tif'_index =192: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00193.tif'_index =193: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00194.tif'_index =194: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00195.tif'_index =195: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00196.tif'_index =196: ty

os.path.basename(_file) ='Image019_00279.tif'_index =279: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00280.tif'_index =280: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00281.tif'_index =281: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00282.tif'_index =282: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00283.tif'_index =283: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00284.tif'_index =284: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00285.tif'_index =285: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00286.tif'_index =286: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00287.tif'_index =287: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00288.tif'_index =288: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00289.tif'_index =289: ty

os.path.basename(_file) ='Image019_00369.tif'_index =369: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00370.tif'_index =370: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00371.tif'_index =371: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00372.tif'_index =372: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00373.tif'_index =373: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00374.tif'_index =374: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00375.tif'_index =375: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00376.tif'_index =376: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00377.tif'_index =377: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00378.tif'_index =378: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00379.tif'_index =379: ty

os.path.basename(_file) ='Image019_00473.tif'_index =473: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00474.tif'_index =474: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00475.tif'_index =475: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00476.tif'_index =476: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00477.tif'_index =477: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00478.tif'_index =478: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00479.tif'_index =479: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00480.tif'_index =480: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00481.tif'_index =481: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00482.tif'_index =482: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00483.tif'_index =483: ty

os.path.basename(_file) ='Image019_00562.tif'_index =562: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00563.tif'_index =563: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00564.tif'_index =564: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00565.tif'_index =565: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00566.tif'_index =566: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00567.tif'_index =567: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00568.tif'_index =568: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00569.tif'_index =569: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00570.tif'_index =570: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00571.tif'_index =571: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00572.tif'_index =572: ty

os.path.basename(_file) ='Image019_00652.tif'_index =652: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00653.tif'_index =653: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00654.tif'_index =654: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00655.tif'_index =655: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00656.tif'_index =656: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00657.tif'_index =657: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00658.tif'_index =658: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00659.tif'_index =659: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00660.tif'_index =660: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00661.tif'_index =661: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00662.tif'_index =662: ty

os.path.basename(_file) ='Image019_00746.tif'_index =746: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00747.tif'_index =747: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00748.tif'_index =748: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00749.tif'_index =749: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00750.tif'_index =750: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00751.tif'_index =751: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00752.tif'_index =752: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00753.tif'_index =753: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00754.tif'_index =754: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00755.tif'_index =755: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00756.tif'_index =756: ty

os.path.basename(_file) ='Image019_00840.tif'_index =840: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00841.tif'_index =841: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00842.tif'_index =842: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00843.tif'_index =843: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00844.tif'_index =844: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00845.tif'_index =845: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00846.tif'_index =846: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00847.tif'_index =847: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00848.tif'_index =848: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00849.tif'_index =849: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00850.tif'_index =850: ty

os.path.basename(_file) ='Image019_00943.tif'_index =943: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00944.tif'_index =944: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00945.tif'_index =945: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00946.tif'_index =946: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00947.tif'_index =947: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00948.tif'_index =948: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00949.tif'_index =949: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00950.tif'_index =950: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00951.tif'_index =951: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00952.tif'_index =952: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_00953.tif'_index =953: ty

os.path.basename(_file) ='Image019_01031.tif'_index =1031: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01032.tif'_index =1032: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01033.tif'_index =1033: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01034.tif'_index =1034: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01035.tif'_index =1035: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01036.tif'_index =1036: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01037.tif'_index =1037: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01038.tif'_index =1038: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01039.tif'_index =1039: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01040.tif'_index =1040: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01041.tif'_inde

os.path.basename(_file) ='Image019_01134.tif'_index =1134: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01135.tif'_index =1135: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01136.tif'_index =1136: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01137.tif'_index =1137: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01138.tif'_index =1138: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01139.tif'_index =1139: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01140.tif'_index =1140: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01141.tif'_index =1141: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01142.tif'_index =1142: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01143.tif'_index =1143: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01144.tif'_inde

os.path.basename(_file) ='Image019_01237.tif'_index =1237: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01238.tif'_index =1238: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01239.tif'_index =1239: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01240.tif'_index =1240: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01241.tif'_index =1241: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01242.tif'_index =1242: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01243.tif'_index =1243: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01244.tif'_index =1244: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01245.tif'_index =1245: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01246.tif'_index =1246: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01247.tif'_inde

os.path.basename(_file) ='Image019_01326.tif'_index =1326: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01327.tif'_index =1327: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01328.tif'_index =1328: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01329.tif'_index =1329: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01330.tif'_index =1330: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01331.tif'_index =1331: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01332.tif'_index =1332: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01333.tif'_index =1333: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01334.tif'_index =1334: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01335.tif'_index =1335: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01336.tif'_inde

os.path.basename(_file) ='Image019_01419.tif'_index =1419: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01420.tif'_index =1420: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01421.tif'_index =1421: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01422.tif'_index =1422: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01423.tif'_index =1423: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01424.tif'_index =1424: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01425.tif'_index =1425: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01426.tif'_index =1426: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01427.tif'_index =1427: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01428.tif'_index =1428: type(_data) =<class 'numpy.memmap'>
os.path.basename(_file) ='Image019_01429.tif'_inde