In [1]:
import numpy as np

In [4]:
reference_index = np.arange(10)
reference_index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
data1 = np.arange(0, 100, 10)
data1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
data2 = np.arange(0, 100, 20)
data2

array([ 0, 20, 40, 60, 80])

In [25]:
index_of_bin_in_reference_index = [0]
for _bin in data2:
    result = np.where(_bin < data1)
    index_of_bin_in_reference_index.append(result[0][0])

In [26]:
index_of_bin_in_reference_index

[0, 1, 3, 5, 7, 9]

# method 2 

In [81]:
original_tof_array = np.array([1.12, 11.36, 21.60, 31.84, 42.08, 52.32])
bin_tof_array = np.array([1.12, 6.12, 11.12, 16.12, 21.12, 26.12, 31.12, 36.12, 41.12, 46.12, 51.12, 56.12])

In [82]:
# original_tof_array = np.arange(0,10,1)
# print(f"original_tof_array: {original_tof_array}")
# bin_tof_array = np.arange(0,11,2)
# print(f"bin_tof_array: {bin_tof_array}")

In [88]:
index_of_bins_in_original_array = [[] for _ in np.arange(len(bin_tof_array))]

In [89]:
for _file_index, _bin in enumerate(original_tof_array):
    result1 = np.where(_bin >= bin_tof_array)
    index = result1[0][-1]
    index_of_bins_in_original_array[index].append(_file_index)

In [90]:
index_of_bins_in_original_array

[[0], [], [1], [], [2], [], [3], [], [4], [], [5], []]

# Create linear file index bin array 

In [1]:
import numpy as np

In [58]:
original_file_index_array = np.arange(20)
print(f"original_file_index_array: {original_file_index_array}")
number_of_files = len(original_file_index_array)

bin_value = 6

new_index_array = np.arange(0, number_of_files, bin_value)
if new_index_array[-1] <= (number_of_files-1):
    new_index_array = np.append(new_index_array, new_index_array[-1] + bin_value)
    
print(f"new_index_array: {new_index_array}")

original_file_index_array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
new_index_array: [ 0  6 12 18 24]


I'm looking for something like 
[[0,1],[2,3],[4,5]....]

In [59]:
bins_with_index_of_file_index = [[] for _ in np.arange(len(new_index_array)-1)]
print(f"bins_with_index_of_file_index: {bins_with_index_of_file_index}")

bins_with_index_of_file_index: [[], [], [], []]


In [60]:
for _file_index, _bin in enumerate(original_file_index_array):
#     print(f"_file_index:{_file_index} and _bin:{_bin}")
#     print(f"new_index_array: {new_index_array}")
    result = np.where(_bin >= new_index_array)
#     print(f"-> result: {result}")

    index = result[0][-1]
    bins_with_index_of_file_index[index].append(_file_index)

In [61]:
print(f"bins_with_index_of_file_index: {bins_with_index_of_file_index}")

bins_with_index_of_file_index: [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19]]
