For an experiment, we had to set up the rotation stages in a way that could minimize the issues due to beam off time.

First list will set up the rotation stage for 5 angles (for example)
then 10 for the next one.....

In [1]:
import numpy as np

In [6]:
full_list_angle = np.linspace(0, 180., num=48)
assert len(full_list_angle) == 48

In [8]:
full_list_index = np.arange(len(full_list_angle))
assert len(full_list_index) == 48

First Run of measurements

In [21]:
first_run_angle_mod = 10
index_first_run = [index for index in full_list_index if (index % first_run_angle_mod == 0)]
list_first_run = full_list_angle[index_first_run]
list_first_run

array([  0.        ,  38.29787234,  76.59574468, 114.89361702,
       153.19148936])

Second run of measurements

In [28]:
second_run_angle_mod = 3
index_second_run = [index for index in full_list_index if (index % second_run_angle_mod == 0) and (index not in index_first_run)]
list_second_run = full_list_angle[index_second_run]
list_second_run

array([ 11.4893617 ,  22.9787234 ,  34.46808511,  45.95744681,
        57.44680851,  68.93617021,  80.42553191,  91.91489362,
       103.40425532, 126.38297872, 137.87234043, 149.36170213,
       160.85106383, 172.34042553])

Third run of measurements

In [33]:
index_third_run = [index for index in full_list_index if  
                   (index not in index_first_run) and
                  (index not in index_second_run)]
list_third_run = full_list_angle[index_third_run]
list_third_run

array([  3.82978723,   7.65957447,  15.31914894,  19.14893617,
        26.80851064,  30.63829787,  42.12765957,  49.78723404,
        53.61702128,  61.27659574,  65.10638298,  72.76595745,
        84.25531915,  88.08510638,  95.74468085,  99.57446809,
       107.23404255, 111.06382979, 118.72340426, 122.55319149,
       130.21276596, 134.04255319, 141.70212766, 145.53191489,
       157.0212766 , 164.68085106, 168.5106383 , 176.17021277,
       180.        ])

In [34]:
len(list_firs_run) + len(list_second_run) + len(list_third_run)

48