In [49]:
import numpy as np
import scipy.ndimage
import scipy.signal

In [50]:
test_data = np.array([[1, 10, 11], [9, 2, 1], [1, 30, 15]])
kernel = np.ones((2, 2))/4

https://www.allaboutcircuits.com/technical-articles/two-dimensional-convolution-in-image-processing/

# convolve with ndimage

In [48]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='reflect')
print(output_array)

[[ 5  6  6]
 [10 12  8]
 [15 22 15]]


In [46]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='constant', cval=0)
print(output_array)

[[ 5  6  3]
 [10 12  4]
 [ 7 11  3]]


In [40]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='nearest')
print(output_array)

[[ 5  6  6]
 [10 12  8]
 [15 22 15]]


In [41]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='mirror')
print(output_array)

[[ 5  6  6]
 [10 12 12]
 [10 12 12]]


In [42]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='wrap')
print(output_array)

[[ 5  6  5]
 [10 12  6]
 [10 16  7]]


# convolve with signal

In [76]:
kernel = np.ones((2, 2))/4

In [77]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='fill', fillvalue=0)
print(output_array)

[[ 0.25  2.75  5.25]
 [ 2.5   5.5   6.  ]
 [ 2.5  10.5  12.  ]]


In [78]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='wrap')
print(output_array)

[[ 7.  10.5 16.5]
 [ 5.5  5.5  6. ]
 [ 6.5 10.5 12. ]]


In [79]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='symm')
print(output_array)

[[ 1.   5.5 10.5]
 [ 5.   5.5  6. ]
 [ 5.  10.5 12. ]]


In [8]:
# gaussian_filter