In [49]:
import numpy as np
import scipy.ndimage
import scipy.signal

In [94]:
test_data = np.array([[1, 10, 11], [9, 2, 1], [1, 30, 15],[20, 2, 3]])
kernel = np.ones((3, 3))/9

https://www.allaboutcircuits.com/technical-articles/two-dimensional-convolution-in-image-processing/

# convolve with ndimage

In [95]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='reflect')
print(output_array)

[[ 4  6  7]
 [ 7  8 10]
 [10  9  7]
 [12 10  8]]


In [96]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='constant', cval=0)
print(output_array)

[[2 3 2]
 [5 8 7]
 [7 9 5]
 [5 7 5]]


In [97]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='nearest')
print(output_array)

[[ 4  6  7]
 [ 7  8 10]
 [10  9  7]
 [12 10  8]]


In [98]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='mirror')
print(output_array)

[[ 5  5  4]
 [10  8 12]
 [10  9  9]
 [16 12 17]]


In [99]:
output_array = scipy.ndimage.convolve(test_data, kernel, mode='wrap')
print(output_array)

[[ 6  6  6]
 [ 8  8  8]
 [ 9  9  9]
 [10 10 10]]


# convolve with signal

In [100]:
kernel = np.ones((3, 3))/9

In [101]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='fill', fillvalue=0)
print(output_array)

[[2.44444444 3.77777778 2.66666667]
 [5.88888889 8.88888889 7.66666667]
 [7.11111111 9.22222222 5.88888889]
 [5.88888889 7.88888889 5.55555556]]


In [102]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='wrap')
print(output_array)

[[ 6.55555556  6.55555556  6.55555556]
 [ 8.88888889  8.88888889  8.88888889]
 [ 9.22222222  9.22222222  9.22222222]
 [10.33333333 10.33333333 10.33333333]]


In [103]:
output_array = scipy.signal.convolve2d(test_data, kernel, mode='same', boundary='symm')
print(output_array)

[[ 4.88888889  6.22222222  7.55555556]
 [ 7.11111111  8.88888889 10.66666667]
 [10.44444444  9.22222222  8.        ]
 [12.88888889 10.66666667  8.44444444]]


In [104]:
# gaussian_filter