In [1]:
a=['1 2','3 4','5 6']

In [6]:
_row_0 = a[0].split(' ')
print(_row_0)
nbr_columns = len(_row_0)
print("nbr_columns: %d" %nbr_columns)

['1', '2']
nbr_columns: 2


In [7]:
final_array = []

In [9]:
for _row in range(len(a)):
    _row_split = a[_row].split(' ')
    final_array.append(_row_split)

In [10]:
print(final_array)

[['1', '2'], ['3', '4'], ['5', '6']]


In [29]:
a=np.zeros((2,2))

NameError: name 'np' is not defined

In [18]:
print(final_array[0][1])      

2


In [21]:
b=[[1,2];[3,4]]

SyntaxError: invalid syntax (<ipython-input-21-e8006c9e4ece>, line 1)

In [20]:
b

[[1, 2], [3, 4]]

In [30]:
import numpy as np

In [42]:
file = "/Users/j35/git/braggedge/tests/data/tof.txt"

In [43]:
from numpy import genfromtxt

In [46]:
my_data = genfromtxt(file, delimiter='')

In [47]:
my_data

array([[  9.60000000e-07,   2.13700000e+03],
       [  1.12000000e-05,   1.98800000e+03],
       [  2.14400000e-05,   1.97900000e+03],
       [  3.16800000e-05,   2.07800000e+03],
       [  4.19200000e-05,   2.06500000e+03],
       [  5.21600000e-05,   2.07700000e+03],
       [  6.24000000e-05,   1.92900000e+03],
       [  7.26400000e-05,   2.03000000e+03],
       [  8.28800000e-05,   2.14000000e+03],
       [  9.31200000e-05,   2.17900000e+03],
       [  1.03360000e-04,   2.07500000e+03],
       [  1.13600000e-04,   2.12600000e+03],
       [  1.23840000e-04,   2.05500000e+03],
       [  1.34080000e-04,   2.10300000e+03],
       [  1.44320000e-04,   2.05400000e+03],
       [  1.54560000e-04,   2.15200000e+03],
       [  1.64800000e-04,   2.11600000e+03],
       [  1.75040000e-04,   2.10000000e+03],
       [  1.85280000e-04,   2.24200000e+03],
       [  1.95520000e-04,   2.13100000e+03],
       [  2.05760000e-04,   2.28200000e+03],
       [  2.16000000e-04,   2.23500000e+03],
       [  

In [37]:
my_data

array([[  1.,  20.],
       [  2.,  21.],
       [  3.,  22.],
       [  4.,  23.],
       [  5.,  24.],
       [  6.,  25.],
       [  7.,  26.],
       [  8.,  27.],
       [  9.,  28.],
       [ 10.,  29.],
       [ 11.,  30.],
       [ 11.,  31.],
       [ 12.,  32.],
       [ 13.,  33.],
       [ 14.,  34.],
       [ 15.,  35.],
       [ 16.,  36.]])

In [38]:
my_data.shape()

TypeError: 'tuple' object is not callable

In [39]:
my_data.shape

(17, 2)

In [41]:
my_data[:,0
    ]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        11.,  12.,  13.,  14.,  15.,  16.])