In [1]:
import numpy as np

In [25]:
a1 = np.array([1,2,3,4,5,6,7,8,9,20])
a2 = np.linspace(1,10,10)+10
a3 = np.linspace(1,10,10)+20

print("a1:", a1)
print("a2:", a2)
print("a3:", a3)

a1: [ 1  2  3  4  5  6  7  8  9 20]
a2: [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
a3: [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]


### add

In [26]:
a_add = np.add(a1,a2)
a_add = np.add(a_add, a3)
print(a_add)

[ 33.  36.  39.  42.  45.  48.  51.  54.  57.  70.]


### mean

In [27]:
b = np.array([a1, a2, a3])
print("b: ", b)

b:  [[  1.   2.   3.   4.   5.   6.   7.   8.   9.  20.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]]


In [28]:
a_median = np.median(b, axis=0)
print("a_median: ", a_median)

a_median:  [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
