In [2]:
import numpy as np

In [25]:
a1 = np.array([1,2,3,4,5,6,7,8,9,20])
a2 = np.linspace(1,10,10)+10
a3 = np.linspace(1,10,10)+20

print("a1:", a1)
print("a2:", a2)
print("a3:", a3)

a1: [ 1  2  3  4  5  6  7  8  9 20]
a2: [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
a3: [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]


### add

In [26]:
a_add = np.add(a1,a2)
a_add = np.add(a_add, a3)
print(a_add)

[ 33.  36.  39.  42.  45.  48.  51.  54.  57.  70.]


### mean

In [27]:
b = np.array([a1, a2, a3])
print("b: ", b)

b:  [[  1.   2.   3.   4.   5.   6.   7.   8.   9.  20.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]]


In [28]:
a_median = np.median(b, axis=0)
print("a_median: ", a_median)

a_median:  [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


4D mean

In [25]:
data_tof1 = np.array([[1,2,3],[3,4,5]])
data_tof2 = np.array([[6,7,8],[9,10,11]])
data_tof3 = np.array([[11,12,13],[13,14,15]])
big_array_1 = np.array([data_tof1, data_tof2, data_tof3])
big_array_2 = big_array_1 + 10
big_array_3 = big_array_1 + 15

In [36]:
print(big_array_1)
print(big_array_2)
print(big_array_3)


[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[11 12 13]
  [13 14 15]]]
[[[11 12 13]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[21 22 23]
  [23 24 25]]]
[[[16 17 18]
  [18 19 20]]

 [[21 22 23]
  [24 25 26]]

 [[26 27 28]
  [28 29 30]]]


In [37]:
full_array = np.array([big_array_1, big_array_2, big_array_3])
np.shape(full_array)

(3, 3, 2, 3)

In [38]:
print(full_array)

[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[11 12 13]
   [13 14 15]]]


 [[[11 12 13]
   [13 14 15]]

  [[16 17 18]
   [19 20 21]]

  [[21 22 23]
   [23 24 25]]]


 [[[16 17 18]
   [18 19 20]]

  [[21 22 23]
   [24 25 26]]

  [[26 27 28]
   [28 29 30]]]]


In [32]:
np.shape(np.mean(full_array, axis=0))

(3, 2, 3)

In [39]:
print(np.mean(full_array, axis=0))

[[[ 9.33333333 10.33333333 11.33333333]
  [11.33333333 12.33333333 13.33333333]]

 [[14.33333333 15.33333333 16.33333333]
  [17.33333333 18.33333333 19.33333333]]

 [[19.33333333 20.33333333 21.33333333]
  [21.33333333 22.33333333 23.33333333]]]
