# Save data using a 'secret data format' in a 'secret location'

In [6]:
import numpy as np
from tempfile import TemporaryFile

In [24]:
?np.savez

In [7]:
x = np.arange(10)
y = np.sin(x)

In [9]:

outfile = TemporaryFile()
np.savez(outfile, x, y)

In [10]:
outfile.seek(0)

0

In [23]:
npzfile = np.load(outfile)

In [12]:
npzfile.files

['arr_1', 'arr_0']

In [13]:
npzfile['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
npzfile['arr_1']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

# Add label to the data set

In [17]:
outfile = TemporaryFile()
np.savez(outfile, first_column=x, second_column=y)

In [18]:
outfile.seek(0)

0

In [19]:
npzfile = np.load(outfile)

In [20]:
npzfile.files

['first_column', 'second_column']

In [21]:
npzfile['first_column']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])