In [3]:
import numpy as np

In [4]:
data_float = np.fromstring('1 3 2 4 3 5 4 6 5 7 6 8', dtype=float, sep=' ')

In [5]:
print(data_float)

[ 1.  3.  2.  4.  3.  5.  4.  6.  5.  7.  6.  8.]


In [6]:
data_int = np.fromstring('1 3 2 4 3 5 4 6 5 7 6 8', dtype=int, sep=' ')

In [7]:
print(data_int)

[1 3 2 4 3 5 4 6 5 7 6 8]


In [8]:
np.savetxt?

In [9]:
np.savetxt('testing_savetxt.txt', data_int)

In [11]:
header = 'this should be the first line'
footer = 'this should be the last line'
comments = '# '
fmt = '%.4f'
np.savetxt('more_complex_savetxt.txt', data_float, fmt=fmt, header=header, footer=footer, comments=comments)

In [12]:
header = 'this should be the first line'
footer = 'this should be the last line'
comments = '# '
fmt = '%.4f'
np.savetxt('more_complex_savetxt.txt', data_int, fmt=fmt, header=header, footer=footer, comments=comments)

# 2D array

In [14]:
data_2d = np.arange(20).reshape((4,5))

In [15]:
print(data_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
print(type(data_2d))

<class 'numpy.ndarray'>


In [16]:
np.savetxt('data_2d_savetxt.txt', data_2d, fmt=fmt, header=header, footer=footer, comments=comments)

# Manually created 2D array

In [25]:
my_data_2d = np.array([[4,10,20,30],[10,  11,  12, 14]])

In [26]:
print(my_data_2d)

[[ 4 10 20 30]
 [10 11 12 14]]


In [27]:
print(type(my_data_2d))

<class 'numpy.ndarray'>


In [28]:
np.savetxt('my_data_2d_savetxt.txt', my_data_2d, fmt=fmt, header=header, footer=footer, comments=comments)