[numpy.isclose reference document](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html)

In [2]:
import numpy as np

In [38]:
angles = np.arange(0,11,1)
angles

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
angles = angles[..., np.newaxis]
angles


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [40]:
diff_matrix = angles.T - angles
diff_matrix

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8],
       [ -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5],
       [ -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [ -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]])

In [41]:
np.isclose(diff_matrix, 9, atol=1e-3)

array([[False, False, False, False, False, False, False, False, False,
         True, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, Fal

In [42]:
np.where(np.isclose(diff_matrix, 9, atol=1e-3))

(array([0, 1]), array([ 9, 10]))

In [46]:
idx_lowrange, idx_highrange = np.where(np.isclose(diff_matrix, 9, atol=1e-3))

In [47]:
idx_lowrange

array([0, 1])

In [48]:
print(idx_highrange)

[ 9 10]
