In [2]:
import numpy as np

In [6]:
my_array = np.array([[1, 2], [3, 4]])

In [7]:
np.tile(my_array, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [8]:
np.tile(my_array, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [12]:
np.tile(my_array, [1, 1, 2])

array([[[1, 2, 1, 2],
        [3, 4, 3, 4]]])

In [14]:
np.tile(np.atleast_2d(my_array), [1,2])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [15]:
np.tile(my_array, [1,2])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [18]:
np.tile(np.atleast_3d(my_array), [1,1,2])

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [19]:
np.tile(np.atleast_3d(my_array), 3)

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [21]:
np.tile(np.atleast_3d(my_array), [1,3])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [28]:
a = np.tile(np.atleast_3d(my_array), [1, 1, 3])
a

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [29]:
a[:, :, 0]

array([[1, 2],
       [3, 4]])