In [2]:
import numpy as np

In [3]:
array = np.arange(10)

In [4]:
w = np.where(array == 5)

In [5]:
w

(array([5]),)

In [6]:
array[w] = 20


In [7]:
array


array([ 0,  1,  2,  3,  4, 20,  6,  7,  8,  9])

# empty where? 

In [17]:
v = np.where(array == 30)

In [18]:
array[v] = 100

In [19]:
type(v)

tuple

In [20]:
array

array([ 0,  1,  2,  3,  4, 20,  6,  7,  8,  9])

# with None 

In [25]:
my_array = list(["1","2","3","4","5","6","7"])
my_array[3] = None
my_array

['1', '2', '3', None, '5', '6', '7']

In [32]:
ww = np.where(my_array == None)

In [31]:
ww

(array([], dtype=int64),)

In [33]:
cleaned_array = []
for _x in my_array:
    if _x == None:
        cleaned_array.append(np.NaN)
    else:
        cleaned_array.append(_x)
        

In [34]:
cleaned_array

['1', '2', '3', nan, '5', '6', '7']